const moment = require("moment-timezone");
const { db } = require("../../connect");
const axios = require("axios");
const dotenv = require("dotenv");
dotenv.config();

const cgonePayBaseURL = process.env.cgonePayBaseURL;
const Token = process.env.cgonePayToken;
const apiClient = axios.create({
  baseURL: cgonePayBaseURL,
});

const getDataFromcgonePayClientApi = (endpoint, params = {}) => {
  return apiClient
    .get(endpoint, {
      params: {
        Apitoken: Token,
        ...params,
      },
    })
    .then((response) => {
      return response.data;
    })
    .catch((error) => {
      console.error("Error fetching data from client API:", error.message);
      throw error;
    });
};

const cgonePayBalance = (req, res) => {
  const endpoint = "/Balance.aspx";

  getDataFromcgonePayClientApi(endpoint, {})
    .then((data) => {
      res.json(data);
    })
    .catch((error) => {
      console.error(
        "Error details:",
        error.response ? error.response.data : error.message
      );
      res.status(500).send("Error fetching data from client API");
    });
};

const operatorMapping = {
  Airtel: { code: "3", category: "Prepaid" },
  "BSNL STV": { code: "151", category: "Prepaid" },
  "BSNL TOPUP": { code: "5", category: "Prepaid" },
  "Airtel Postpaid": { code: "41", category: "Postpaid" },
  "BSNL Postpaid": { code: "104", category: "Postpaid" },
  Jio: { code: "26", category: "Prepaid" },
  "Jio Postpaid": { code: "103", category: "Postpaid" },
  Vi: { code: "2", category: "Prepaid" },
  "Vi Postpaid": { code: "114", category: "Postpaid" },
  "Dish TV": { code: "35", category: "DTH" },
  "Tata Sky": { code: "31", category: "DTH" },
  Videocon: { code: "33", category: "DTH" },
  "Sun Direct": { code: "36", category: "DTH" },
  "Airtel DTH": { code: "34", category: "DTH" },
};

const cgonepayRecharge = (req, res) => {
  const { number, amount, operatorName, recharge_Type, created_by_userid } =
    req.body;
  const createdAt = moment().tz("Asia/Kolkata").format("YYYY-MM-DD HH:mm:ss");
  const updatedAt = moment().tz("Asia/Kolkata").format("YYYY-MM-DD HH:mm:ss");
  const providerName = "cgonePay";

  let responseSent = false; // Flag to track if response has been sent

  if (!number || !amount || !operatorName) {
    return res.status(400).json({ error: "All fields are required" });
  }

  const operatorDetails = operatorMapping[operatorName];
  const randomOutletID = Math.floor(100000 + Math.random() * 900000).toString();

  // Step 1: Fetch balance
  getDataFromcgonePayClientApi("/Balance.aspx", {})
    .then((balanceData) => {
      // if (balanceData?.bal < amount) {
      //   if (!responseSent) { // Check if response was already sent
      //     responseSent = true;
      //     return res.status(400).json({ message: "Recharge failed", error: "Insufficient balance in Recharge Api" });
      //   }
      // }

      // Step 2: Map operator name to code
      if (!operatorDetails) {
        if (!responseSent) {
          responseSent = true;
          return res.status(400).json({ error: "Invalid operator name" });
        }
      }

      // Step 3: Insert initial row to generate orderid
      const insertQuery =
        "INSERT INTO recharges (mobile_no, amount, operator_name, providerName, recharge_Type, created_by_userid, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)";
      const values = [
        number,
        amount,
        operatorName,
        providerName,
        recharge_Type,
        created_by_userid,
        createdAt,
      ];

      return new Promise((resolve, reject) => {
        db.query(insertQuery, values, (err, result) => {
          if (err) {
            console.error("Error generating orderid:", err.message);
            return reject(err);
          }

          const autoGeneratedOrderId = result.insertId;
          const formattedOrderId = `REC${String(autoGeneratedOrderId).padStart(
            6,
            "0"
          )}`;
          resolve({ orderid: formattedOrderId, id: autoGeneratedOrderId });
        });
      });
    })
    .then(({ orderid, id }) => {
      // Step 4: Perform recharge with the generated orderid
      return getDataFromcgonePayClientApi("/Recharge.aspx", {
        Amount: amount,
        OperatorCode: operatorDetails.code,
        Number: number,
        ClientId: orderid,
      }).then((rechargeData) => {
        return { rechargeData, id, orderid };
      });
    })
    .then(({ rechargeData, id, orderid }) => {
      // Step 5: Update the recharge row with API response data
      const updateQuery =
        "UPDATE recharges SET opcode = ?, status = ?, transaction_id = ?, opid = ?, orderid = ?, message = ?, updated_at = ? WHERE id = ?";
      // const getStatus = () => {
      //   if (rechargeData?.status == 1) {
      //     return "Pending";
      //   } else if (rechargeData?.status == 2) {
      //     return "Success";
      //   } else {
      //     return "Failure";
      //   }
      // };
      // const Status = getStatus();

      const updateValues = [
        operatorDetails?.code,
        rechargeData?.STATUS,
        rechargeData?.TRANSACTIONID,
        rechargeData?.OPERATORID,
        orderid,
        rechargeData?.MESSAGE,
        updatedAt,
        id,
      ];

      db.query(updateQuery, updateValues, (err, result) => {
        if (err) {
          console.error("Error updating recharge data:", err.message);
          if (!responseSent) {
            responseSent = true;
            return res
              .status(500)
              .json({ error: "Database update error", message: err.message });
          }
        }

        // Step 6: Respond with the recharge data and orderid
        if (rechargeData?.STATUS == "SUCCESS") {
          if (!responseSent) {
            responseSent = true;
            return res.json({
              message: "Recharge successful",
              rechargeData,
              orderid: rechargeData?.CLIENTID,
            });
          }
        } else if (rechargeData?.STATUS == "IN PROCESS") {
          if (!responseSent) {
            responseSent = true;
            return res.json({
              message: "Recharge IN PROCESS",
              rechargeData,
              orderid: rechargeData?.CLIENTID,
            });
          }
        } else {
          if (!responseSent) {
            responseSent = true;
            return res.json({
              message: "Recharge failed",
              rechargeData,
              orderid: rechargeData?.CLIENTID,
            });
          }
        }
      });
    })
    .catch((error) => {
      console.error("Error during recharge process:", error.message);
      if (!responseSent) {
        responseSent = true;
        return res.status(500).json({
          error: "Error during recharge process",
          message: error.message,
        });
      }
    });
};

const cgonePayRechargeStatusCheck = (req, res) => {
  const { transaction_id } = req.body;
  const endpoint = "/rechargestatus.aspx";
  // Generate random 6-digit number for OutletID
  // const randomOutletID = Math.floor(100000 + Math.random() * 900000).toString();

  getDataFromcgonePayClientApi(endpoint, {
    ClientId: transaction_id,
  })
    .then((data) => {
      res.json(data);
    })
    .catch((error) => {
      console.error(
        "Error details:",
        error.response ? error.response.data : error.message
      );
      res.status(500).send("Error fetching data from client API");
    });
};

module.exports = {
  cgonePayBalance,
  cgonepayRecharge,
  cgonePayRechargeStatusCheck,
};
